---
layout: post
title: Understanding defer in Go
network: digitalocean
date: September 27, 2019 at 07:23PM
url: https://www.digitalocean.com/community/tutorials/understanding-defer-in-go
image: http://ifttt.com/images/no_image_card.png
tags: docker
feedtitle: DigitalOcean Community Tutorials
feedurl: https://www.digitalocean.com/community/tutorials
author: DigitalOcean
---
<h3 id="introduction">Introduction</h3>

<p>Go has many of the common control-flow keywords found in other programming languages such as <code>if</code>, <code>switch</code>, <code>for</code>, etc. One keyword that isn&rsquo;t found in most other programming languages is <code>defer</code>, and though it&rsquo;s less common you&rsquo;ll quickly see how useful it can be in your programs.</p>

<p>One of the primary uses of a <code>defer</code> statement is for cleaning up resources, such as open files, network connections, and <a href="https://en.wikipedia.org/wiki/Handle_(computing)">database handles</a>. When your program is finished with these resources, it&rsquo;s important to close them to avoid exhausting the program&rsquo;s limits and to allow other programs access to those resources. <code>defer</code> makes our code cleaner and less error prone by keeping the calls to close the file/resource in proximity to the open call.</p>

<p>In this article we will learn how to properly use the <code>defer</code> statement for cleaning up resources as well as several common mistakes that are made when using <code>defer</code>.</p>

<h2 id="what-is-a-defer-statement">What is a <code>defer</code> Statement</h2>

<p>A <code>defer</code> statement adds the <a href="https://www.digitalocean.com/community/tutorials/how-to-define-and-call-functions-in-go">function</a> call following the <code>defer</code> keyword onto a stack. All of the calls on that stack are called when the function in which they were added returns. Because the calls are placed on a stack, they are called in last-in-first-out order.</p>

<p>Let&rsquo;s look at how <code>defer</code> works by printing out some text:</p>
<div class="code-label " title="main.go">main.go</div><pre class="code-pre "><code class="code-highlight language-go">package main

import "fmt"

func main() {
    defer fmt.Println("Bye")
    fmt.Println("Hi")
}
</code></pre>
<p>In the <code>main</code> function, we have two statements. The first statement starts with the <code>defer</code> keyword, followed by a <code>print</code> statement that prints out <code>Bye</code>. The next line prints out <code>Hi</code>.</p>

<p>If we run the program, we will see the following output:</p>
<pre class="code-pre "><code langs=""><div class="secondary-code-label " title="Output">Output</div>Hi
Bye
</code></pre>
<p>Notice that <code>Hi</code> was printed first. This is because any statement that is preceded by the <code>defer</code> keyword isn&rsquo;t invoked until the end of the function in which <code>defer</code> was used.</p>

<p>Let&rsquo;s take another look at the program, and this time we&rsquo;ll add some comments to help illustrate what is happening:</p>
<div class="code-label " title="main.go">main.go</div><pre class="code-pre "><code class="code-highlight language-go">package main

import "fmt"

func main() {
    // defer statement is executed, and places
    // fmt.Println("Bye") on a list to be executed prior to the function returning
    defer fmt.Println("Bye")

    // The next line is executed immediately
    fmt.Println("Hi")

    // fmt.Println*("Bye") is now invoked, as we are at the end of the function scope
}
</code></pre>
<p>The key to understanding <code>defer</code> is that when the <code>defer</code> statement is executed, the arguments to the deferred function are evaluated immediately. When a <code>defer</code> executes, it places the statement following it on a list to be invoked prior to the function returning.</p>

<p>Although this code illustrates the order in which <code>defer</code> would be run, it&rsquo;s not a typical way it would be used when writing a Go program. It&rsquo;s more likely we are using <code>defer</code> to clean up a resource, such as a file handle. Let&rsquo;s look at how to do that next.</p>

<h2 id="using-defer-to-clean-up-resources">Using <code>defer</code> to Clean Up Resources</h2>

<p>Using <code>defer</code> to clean up resources is very common in Go. Let&rsquo;s first look at a program that writes a string to a file but does not use <code>defer</code> to handle the resource clean-up:</p>
<div class="code-label " title="main.go">main.go</div><pre class="code-pre "><code class="code-highlight language-go">package main

import (
    "io"
    "log"
    "os"
)

func main() {
    if err := write("readme.txt", "This is a readme file"); err != nil {
        log.Fatal("failed to write file:", err)
    }
}

func write(fileName string, text string) error {
    file, err := os.Create(fileName)
    if err != nil {
        return err
    }
    _, err = io.WriteString(file, text)
    if err != nil {
        return err
    }
    file.Close()
    return nil
}
</code></pre>
<p>In this program, there is a function called <code>write</code> that will first attempt to create a file. If it has an error, it will return the error and exit the function. Next, it tries to write the string <code>This is a readme file</code> to the specified file. If it receives an error, it will return the error and exit the function. Then, the function will try to close the file and release the resource back to the system. Finally the function returns <code>nil</code> to signify that the function executed without error.</p>

<p>Although this code works, there is a subtle bug. If the call to <code>io.WriteString</code> fails, the function will return without closing the file and releasing the resource back to the system.</p>

<p>We could fix the problem by adding another <code>file.Close()</code> statement, which is how you would likely solve this in a language without <code>defer</code>:</p>
<div class="code-label " title="main.go">main.go</div><pre class="code-pre plain"><code langs="">package main

import (
    "io"
    "log"
    "os"
)

func main() {
    if err := write("readme.txt", "This is a readme file"); err != nil {
        log.Fatal("failed to write file:", err)
    }
}

func write(fileName string, text string) error {
    file, err := os.Create(fileName)
    if err != nil {
        return err
    }
    _, err = io.WriteString(file, text)
    if err != nil {
        <span class="highlight">file.Close()</span>
        return err
    }
    file.Close()
    return nil
}
</code></pre>
<p>Now even if the call to <code>io.WriteString</code> fails, we will still close the file. While this was a relatively easy bug to spot and fix, with a more complicated function, it may have been missed.</p>

<p>Instead of adding the second call to <code>file.Close()</code>, we can use a <code>defer</code> statement to ensure that regardless of which branches are taken during execution, we always call <code>Close()</code>.</p>

<p>Here&rsquo;s the version that uses the <code>defer</code> keyword:</p>
<div class="code-label " title="main.go">main.go</div><pre class="code-pre plain"><code langs="">package main

import (
    "io"
    "log"
    "os"
)

func main() {
    if err := write("readme.txt", "This is a readme file"); err != nil {
        log.Fatal("failed to write file:", err)
    }
}

func write(fileName string, text string) error {
    file, err := os.Create(fileName)
    if err != nil {
        return err
    }
    <span class="highlight">defer file.Close()</span>
    _, err = io.WriteString(file, text)
    if err != nil {
        return err
    }
    return nil
}
</code></pre>
<p>This time we added the line of code: <code>defer file.Close()</code>. This tells the compiler that it should execute the <code>file.Close</code> prior to exiting the function <code>write</code>.</p>

<p>We have now ensured that even if we add more code and create another branch that exits the function in the future, we will always clean up and close the file.</p>

<p>However, we have introduced yet another bug by adding the defer. We are no longer checking the potential error that can be returned from the <code>Close</code> method. This is because when we use <code>defer</code>, there is no way to communicate any return value back to our function.</p>

<p>In Go, it is considered a safe and accepted practice to call <code>Close()</code> more than once without affecting the behavior of your program. If <code>Close()</code> is going to return an error, it will do so the first time it is called. This allows us to call it explicitly in the successful path of execution in our function.</p>

<p>Let&rsquo;s look at how we can both <code>defer</code> the call to <code>Close</code>, and still report on an error if we encounter one.</p>
<div class="code-label " title="main.go">main.go</div><pre class="code-pre plain"><code langs="">package main

import (
    "io"
    "log"
    "os"
)

func main() {
    if err := write("readme.txt", "This is a readme file"); err != nil {
        log.Fatal("failed to write file:", err)
    }
}

func write(fileName string, text string) error {
    file, err := os.Create(fileName)
    if err != nil {
        return err
    }
    defer file.Close()
    _, err = io.WriteString(file, text)
    if err != nil {
        return err
    }

    return <span class="highlight">file.Close()</span>
}
</code></pre>
<p>The only change in this program is the last line in which we return <code>file.Close()</code>. If the call to <code>Close</code> results in an error, this will now be returned as expected to the calling function. Keep in mind that our <code>defer file.Close()</code> statement is also going to run after the <code>return</code> statement. This means that <code>file.Close()</code> is potentially called twice. While this isn&rsquo;t ideal, it is an acceptable practice as it should not create any side effects to your program.</p>

<p>If, however, we receive an error earlier in the function, such as when we call <code>WriteString</code>, the function will return that error, and will also try to call <code>file.Close</code> because it was deferred. Although <code>file.Close</code> may (and likely will) return an error as well, it is no longer something we care about as we received an error that is more likely to tell us what went wrong to begin with.</p>

<p>So far, we have seen how we can use a single <code>defer</code> to ensure that we clean up our resources properly. Next we will see how we can use multiple <code>defer</code> statements for cleaning up more than one resource.</p>

<h2 id="multiple-defer-statements">Multiple <code>defer</code> Statements</h2>

<p>It is normal to have more than one <code>defer</code> statement in a function. Let&rsquo;s create a program that only has <code>defer</code> statements in it to see what happens when we introduce multiple defers:</p>
<div class="code-label " title="main.go">main.go</div><pre class="code-pre "><code class="code-highlight language-go">package main

import "fmt"

func main() {
    defer fmt.Println("one")
    defer fmt.Println("two")
    defer fmt.Println("three")
}
</code></pre>
<p>If we run the program, we will receive the following output:</p>
<pre class="code-pre "><code langs=""><div class="secondary-code-label " title="Output">Output</div>three
two
one
</code></pre>
<p>Notice that the order is the opposite in which we called the <code>defer</code> statements. This is because each deferred statement that is called is stacked on top of the previous one, and then called in reverse when the function exits scope (<em>Last In, First Out</em>).</p>

<p>You can have as many deferred calls as needed in a function, but it is important to remember they will all be called in the opposite order they were executed.</p>

<p>Now that we understand the order in which multiple defers will execute, let&rsquo;s see how we would use multiple defers to clean up multiple resources. We&rsquo;ll create a program that opens a file, writes to it, then opens it again to copy the contents to another file.</p>
<div class="code-label " title="main.go">main.go</div><pre class="code-pre "><code class="code-highlight language-go">package main

import (
    "fmt"
    "io"
    "log"
    "os"
)

func main() {
    if err := write("sample.txt", "This file contains some sample text."); err != nil {
        log.Fatal("failed to create file")
    }

    if err := fileCopy("sample.txt", "sample-copy.txt"); err != nil {
        log.Fatal("failed to copy file: %s")
    }
}

func write(fileName string, text string) error {
    file, err := os.Create(fileName)
    if err != nil {
        return err
    }
    defer file.Close()
    _, err = io.WriteString(file, text)
    if err != nil {
        return err
    }

    return file.Close()
}

func fileCopy(source string, destination string) error {
    src, err := os.Open(source)
    if err != nil {
        return err
    }
    defer src.Close()

    dst, err := os.Create(destination)
    if err != nil {
        return err
    }
    defer dst.Close()

    n, err := io.Copy(dst, src)
    if err != nil {
        return err
    }
    fmt.Printf("Copied %d bytes from %s to %s\n", n, source, destination)

    if err := src.Close(); err != nil {
        return err
    }

    return dst.Close()
}
</code></pre>
<p>We added a new function called <code>fileCopy</code>. In this function, we first open up our source file that we are going to copy from. We check to see if we received an error opening the file. If so, we <code>return</code> the error and exit the function. Otherwise, we <code>defer</code> the closing of the source file we just opened.</p>

<p>Next we create the destination file. Again, we check to see if we received an error creating the file. If so, we <code>return</code> that error and exit the function. Otherwise, we also <code>defer</code> the <code>Close()</code> for the destination file. We now have two <code>defer</code> functions that will be called when the function exits its scope.</p>

<p>Now that we have both files open, we will <code>Copy()</code> the data from the source file to the destination file. If that is successful, we will attempt to close both files. If we receive an error trying to close either file, we will <code>return</code> the error and exit function scope.</p>

<p>Notice that we explicitly call <code>Close()</code> for each file, even though the <code>defer</code> will also call <code>Close()</code>. This is to ensure that if there is an error closing a file, we report the error. It also ensures that if for any reason the function exits early with an error, for instance if we failed to copy between the two files, that each file will still try to close properly from the deferred calls.</p>

<h2 id="conclusion">Conclusion</h2>

<p>In this article we learned about the <code>defer</code> statement, and how it can be used to ensure that we properly clean up system resources in our program. Properly cleaning up system resources will make your program use less memory and perform better. To learn more about where <code>defer</code> is used, read the article on Handling Panics, or explore our entire <a href="https://www.digitalocean.com/community/tutorial_series/how-to-code-in-go">How To Code in Go series</a>.</p>
