---
layout: post
title: Creating Custom Errors in Go
network: digitalocean
date: September 04, 2019 at 04:36PM
url: https://www.digitalocean.com/community/tutorials/creating-custom-errors-in-go
image: http://ifttt.com/images/no_image_card.png
tags: docker
feedtitle: DigitalOcean Community Tutorials
feedurl: https://www.digitalocean.com/community/tutorials
author: DigitalOcean
---
<h3 id="introduction">Introduction</h3>

<p>Go provides two methods to create errors in the standard library, <a href="https://www.digitalocean.com/community/tutorials/handling-errors-in-go#creating-errors"><code>errors.New</code> and <code>fmt.Errorf</code></a>. When communicating more complicated error information to your users, or to your future self when debugging, sometimes these two mechanisms are not enough to adequately capture and report what has happened. To convey this more complex error information and attain more functionality, we can implement the standard library interface type, <a href="https://golang.org/pkg/builtin/#error"><code>error</code></a>.</p>

<p>The syntax for this would be as follows:</p>
<pre class="code-pre "><code class="code-highlight language-go">type error interface {
  Error() string
}
</code></pre>
<p>The <a href="https://golang.org/pkg/builtin/"><code>builtin</code></a> package defines <code>error</code> as an interface with a single <code>Error()</code> method that returns an error message as a string. By implementing this method, we can transform any type we define into an error of our own.</p>

<p>Let&rsquo;s try running the following example to see an implementation of the <code>error</code> interface:</p>
<pre class="code-pre "><code class="code-highlight language-go">package main

import (
    "fmt"
    "os"
)

type MyError struct{}

func (m *MyError) Error() string {
    return "boom"
}

func sayHello() (string, error) {
    return "", &amp;MyError{}
}

func main() {
    s, err := sayHello()
    if err != nil {
        fmt.Println("unexpected error: err:", err)
        os.Exit(1)
    }
    fmt.Println("The string:", s)
}
</code></pre>
<p>We&rsquo;ll see the following output:</p>
<pre class="code-pre "><code langs=""><div class="secondary-code-label " title="Output">Output</div>unexpected error: err: boom
exit status 1
</code></pre>
<p>Here we&rsquo;ve created a new empty struct type, <code>MyError</code>, and defined the <code>Error()</code> method on it. The <code>Error()</code> method returns the string <code>"boom"</code>.</p>

<p>Within <code>main()</code>, we call the function <code>sayHello</code> that returns an empty string and a new instance of <code>MyError</code>. Since <code>sayHello</code> will always return an error, the <code>fmt.Println</code> invocation within the body of the if statement in <code>main()</code> will always execute. We then use <code>fmt.Println</code> to print the short prefix string <code>"unexpected error:"</code> along with the instance of <code>MyError</code> held within the <code>err</code> variable.</p>

<p>Notice that we don&rsquo;t have to directly call <code>Error()</code>, since the <code>fmt</code> package is able to automatically detect that this is an implementation of <code>error</code>. It calls <code>Error()</code> <a href="https://en.wikipedia.org/wiki/Transparency_(human%E2%80%93computer_interaction)">transparently</a> to get the string <code>"boom"</code> and concatenates it with the prefix string <code>"unexpected error: err:"</code>.</p>

<h2 id="collecting-detailed-information-in-a-custom-error">Collecting Detailed Information in a Custom Error</h2>

<p>Sometimes a custom error is the cleanest way to capture detailed error information. For example, let&rsquo;s say we want to capture the status code for errors produced by an HTTP request; run the following program to see an implementation of <code>error</code> that allows us to cleanly capture that information:</p>
<pre class="code-pre "><code class="code-highlight language-go">package main

import (
    "errors"
    "fmt"
    "os"
)

type RequestError struct {
    StatusCode int

    Err error
}

func (r *RequestError) Error() string {
    return fmt.Sprintf("status %d: err %v", r.StatusCode, r.Err)
}

func doRequest() error {
    return &amp;RequestError{
        StatusCode: 503,
        Err:        errors.New("unavailable"),
    }
}

func main() {
    err := doRequest()
    if err != nil {
        fmt.Println(err)
        os.Exit(1)
    }
    fmt.Println("success!")
}
</code></pre>
<p>We will see the following output:</p>
<pre class="code-pre "><code langs=""><div class="secondary-code-label " title="Output">Output</div>status 503: err unavailable
exit status 1
</code></pre>
<p>In this example, we create a new instance of <code>RequestError</code> and provide the status code and an error using the <code>errors.New</code> function from the standard library. We then print this using <code>fmt.Println</code> as in previous examples.</p>

<p>Within the <code>Error()</code> method of <code>RequestError</code>, we use the <code>fmt.Sprintf</code> function to construct a string using the information provided when the error was created.</p>

<h2 id="type-assertions-and-custom-errors">Type Assertions and Custom Errors</h2>

<p>The <code>error</code> interface exposes only one method, but we may need to access the other methods of <code>error</code> implementations to handle an error properly. For example, we may have several custom implementations of <code>error</code> that are temporary and can be retriedâ€”denoted by the presence of a <code>Temporary()</code> method.</p>

<p>Interfaces provide a narrow view into the wider set of methods provided by types, so we must use a <em>type assertion</em> to change the methods that view is displaying, or to remove it entirely.</p>

<p>The following example augments the <code>RequestError</code> shown previously to have a <code>Temporary()</code> method which will indicate whether or not callers should retry the request:</p>
<pre class="code-pre "><code class="code-highlight language-go">package main

import (
    "errors"
    "fmt"
    "net/http"
    "os"
)

type RequestError struct {
    StatusCode int

    Err error
}

func (r *RequestError) Error() string {
    return r.Err.Error()
}

func (r *RequestError) Temporary() bool {
    return r.StatusCode == http.StatusServiceUnavailable // 503
}

func doRequest() error {
    return &amp;RequestError{
        StatusCode: 503,
        Err:        errors.New("unavailable"),
    }
}

func main() {
    err := doRequest()
    if err != nil {
        fmt.Println(err)
        re, ok := err.(*RequestError)
        if ok {
            if re.Temporary() {
                fmt.Println("This request can be tried again")
            } else {
                fmt.Println("This request cannot be tried again")
            }
        }
        os.Exit(1)
    }

    fmt.Println("success!")
}
</code></pre>
<p>We will see the following output:</p>
<pre class="code-pre "><code langs=""><div class="secondary-code-label " title="Output">Output</div>unavailable
This request can be tried again
exit status 1
</code></pre>
<p>Within <code>main()</code>, we call <code>doRequest()</code> which returns an <code>error</code> interface to us. We first print the error message returned by the <code>Error()</code> method. Next, we attempt to expose all methods from <code>RequestError</code> by using the type assertion <code>re, ok := err.(*RequestError)</code>. If the type assertion succeeded, we then use the <code>Temporary()</code> method to see if this error is a temporary error. Since the <code>StatusCode</code> set by <code>doRequest()</code> is <code>503</code>, which matches <code>http.StatusServiceUnavailable</code>, this returns <code>true</code> and causes <code>"This request can be tried again"</code> to be printed. In practice, we would instead make another request rather than printing a message.</p>

<h2 id="wrapping-errors">Wrapping Errors</h2>

<p>Commonly, an error will be generated from something outside of your program such as: a database, a network connection, etc. The error messages provided from these errors don&rsquo;t help anyone find the origin of the error. Wrapping errors with extra information at the beginning of an error message would provide some needed context for successful debugging.</p>

<p>The following example demonstrates how we can attach some contextual information to an otherwise cryptic <code>error</code> returned from some other function:</p>
<pre class="code-pre "><code class="code-highlight language-go">package main

import (
    "errors"
    "fmt"
)

type WrappedError struct {
    Context string
    Err     error
}

func (w *WrappedError) Error() string {
    return fmt.Sprintf("%s: %v", w.Context, w.Err)
}

func Wrap(err error, info string) *WrappedError {
    return &amp;WrappedError{
        Context: info,
        Err:     err,
    }
}

func main() {
    err := errors.New("boom!")
    err = Wrap(err, "main")

    fmt.Println(err)
}
</code></pre>
<p>We will see the following output:</p>
<pre class="code-pre "><code langs=""><div class="secondary-code-label " title="Output">Output</div>main: boom!
</code></pre>
<p><code>WrappedError</code> is a struct with two fields: a context message as a <code>string</code>, and an <code>error</code> that this <code>WrappedError</code> is providing more information about. When the <code>Error()</code> method is invoked, we again use <code>fmt.Sprintf</code> to print the context message, then the <code>error</code> (<code>fmt.Sprintf</code> knows to implicitly call the <code>Error()</code> method as well).</p>

<p>Within <code>main()</code>, we create an error using <code>errors.New</code>, and then we wrap that error using the <code>Wrap</code> function we defined. This allows us to indicate that this <code>error</code> was generated in <code>"main"</code>. Also, since our <code>WrappedError</code> is also an <code>error</code>, we could wrap other <code>WrappedError</code>sâ€”this would allow us to see a chain to help us track down the source of the error. With a little help from the standard library, we can even embed complete stack traces in our errors.</p>

<h2 id="conclusion">Conclusion</h2>

<p>Since the <code>error</code> interface is only a single method, we&rsquo;ve seen that we have great flexibility in providing different types of errors for different situations. This can encompass everything from communicating multiple pieces of information as part of an error all the way to implementing <a href="https://en.wikipedia.org/wiki/Exponential_backoff">exponential backoff</a>. While the error handling mechanisms in Go might on the surface seem simplistic, we can achieve quite rich handling using these custom errors to handle both common and uncommon situations.</p>

<p>Go has another mechanism to communicate unexpected behavior, panics. In our next article in the error handling series, we will examine panicsâ€”what they are and how to handle them.</p>
